In [2]:
import re
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
def vectorize(fen):
    data = re.split(" ", fen)
    rows= re.split("/", data[0])
    turn = data[1]
    can_castle = data[2]
    passant = data[3]
    half_moves = data[4]
    full_moves = data[5]
    
    bit_vector = np.zeros((13, 8, 8), dtype=np.uint8)
    #what layer each piece is found on
    piece_to_layer = {
            'R': 1,
            'N': 2,
            'B': 3,
            'Q': 4,
            'K': 5,
            'P': 6,
            'p': 7,
            'k': 8,
            'q': 9,
            'b': 10,
            'n': 11,
            'r': 12
        }
    #find each piece based on type
    for r,value in enumerate(rows):
        colum = 0
        for piece in value:
            if piece in piece_to_layer:
                bit_vector[piece_to_layer[piece],r,colum] =1
                colum += 1
            else:
                colum += int(piece)
    
    if turn.lower() == 'w':
        bit_vector [0,7,4] =1
    else:
        bit_vector [0,0,4] =1
        
    #where each castle bit is located
    castle ={
        'k': (0,0),
        'q': (0,7),
        'K': (7,0),
        'Q': (7,7),
        }

    for value in can_castle:
        if value in castle:
            bit_vector[0,castle[value][0],castle[value][1]] = 1
    
    #put en-passant square in the vector
    if passant != '-':
        bit_vector[0,  5 if (int(passant[1])-1 == 3) else 2 , ord(passant[0]) - 97,] = 1
        
    return bit_vector

In [4]:
print(vectorize(r'rnbqkb1r/ppp1pppp/3p4/3nP3/3P4/8/PPPK1PPP/RNBQ1BNR b kq - 1 4')[0])
# print(vectorize(r'r3r1k1/pppq2bp/3pp1p1/3P4/2PpP3/6P1/PP1N2K1/R1BQR3 b - e3 0 19')[0])

[[1 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [5]:
def train_neural_network(df):
    # Define the neural network architecture
    model = tf.keras.Sequential([
        tf.keras.layers.Flatten(input_shape=(800, 13, 8, 8)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    # Compile the model
    model.compile(optimizer='rmsprop',
                  loss='mean_squared_error',
                  metrics=['accuracy'])

    ## Get training and testing data
    # Set the train-test split ratio
    train_ratio = 0.8

    # Shuffle the DataFrame
    df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)

    # Calculate the number of samples for training
    train_size = int(len(df_shuffled) * train_ratio)

    # Split the DataFrame into training and testing sets
    train_df = df_shuffled[:train_size]
    test_df = df_shuffled[train_size:]

    # Separate x and y columns
    x_train, x_test = train_df.FEN, train_df.FEN
    y_train, y_test = train_df.Evaluation, test_df.Evaluation

    # x_train = np.asarray(x_train).astype('float32')
    y_train = np.asarray(y_train).astype('float32')


    # Train the model
    model.fit(x_train, y_train, epochs=10, batch_size=1)

    # Evaluate the model on the test data
    loss, accuracy = model.evaluate(x_test, y_test)

    # Print the evaluation metrics
    print(f"Test loss: {loss:.4f}")
    print(f"Test accuracy: {accuracy:.4f}")

In [6]:
df = pd.read_csv('../data/kaggleDataset/chessData.csv')

In [8]:
# Expects data frame with 1 column "FEN", and another "Evaluation"
def train_test_split(df, random, train_size):
    # Shuffle the DataFrame
    df_shuffled = df.sample(frac=1, random_state=random).reset_index(drop=True)

    # Calculate the number of samples for training
    train_size = int(len(df_shuffled) * train_size)

    # Split the DataFrame into training and testing sets
    train_df = df_shuffled[:train_size]
    test_df = df_shuffled[train_size:]

    # Separate x and y columns
    x_train, x_test = train_df.FEN, train_df.FEN
    y_train, y_test = train_df.Evaluation, test_df.Evaluation

    return x_train, x_test, y_train, y_test



In [9]:
x_train, x_test, y_train, y_test = train_test_split(df, random=0, train_size = .75)

TypeError: train_test_split() got an unexpected keyword argument 'random_state'

## Converting the FEN strings

Getting the vectorized version

In [6]:
dfcopy = df.copy().head(1000)

vectorized = dfcopy.FEN.apply(vectorize)  # type: ignore
dfcopy.FEN = vectorized
dfcopy

# Save to CSV?
# dfcopy.to_csv('../data/createdData/vectorized.csv')

FEN Evaluation
0    [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...        -10
1    [[[1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0,...        +56
2    [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...         -9
3    [[[1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0,...        +52
4    [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...        -26
..                                                 ...        ...
995  [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...        +20
996  [[[1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0,...       +135
997  [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...        +84
998  [[[1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0,...       +116
999  [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...        +43

[1000 rows x 2 columns]

## Handling Weird Evaluation Scores

Some are like "#+6", or even stranger like "\ufeff23". Want them all to be +/- integers

In [7]:
# This is to handle weird cases in Evaluation such as "#+6", or "\ufeff23"
def parse_evaluation(value):
    if isinstance(value, str):
        value = re.sub(r'[^0-9+\-]', '', value)  # Remove anything that's not a digit or '+' or '-'
        return int(value.replace('-', '')) * (-1 if '-' in value else 1)
    return value

# Apply the parsing function to the 'Evaluation' column
dfcopy['Evaluation'] =  dfcopy['Evaluation'].apply(parse_evaluation)

In [8]:
type(dfcopy.Evaluation)

pandas.core.series.Series

# Try making the neural network

Hasn't worked so far

In [12]:
# Issue is with the vectorized FEN strings. They aren't converting nicely. Try different things.
dfcopy.FEN

0      [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
1      [[[1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
2      [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
3      [[[1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
4      [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
                             ...                        
995    [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
996    [[[1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
997    [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
998    [[[1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
999    [[[1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 0, 0, 0,...
Name: FEN, Length: 1000, dtype: object

In [11]:
train_neural_network(dfcopy)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).